### ISSUE TITLE
Bracket problem

### ISSUE THREAD

**Issue by andlike** [jsvine/pdfplumber#103]
input：
![image](https://user-images.githubusercontent.com/9100593/55124713-26134800-5142-11e9-8783-5a3b0df01ce0.png)

[20181119.pdf](https://github.com/jsvine/pdfplumber/files/2990770/20181119.pdf)

**Comment by andlike** [comment]
`table_setting = {
    "vertical_strategy": "lines", 
    "horizontal_strategy": "text",
    "explicit_vertical_lines": [],
    "explicit_horizontal_lines": [],
    "snap_tolerance": 3,
    "join_tolerance": 3,
    "edge_min_length": 3,
    "min_words_vertical": 3,
    "min_words_horizontal": 1,
    "keep_blank_chars": False,
    "text_tolerance": 3,
    "text_x_tolerance": None,
    "text_y_tolerance": None,
    "intersection_tolerance": 3,
    "intersection_x_tolerance": None,
    "intersection_y_tolerance": None,
}`

**Comment by kensouchen** [comment]
Might be because a issue with the char arrangement method in the code.

Could you please check whether pdfminer can extract the chart part with correct order?  

if it does extract [2-氟酚 (SS)] in correct order, this should be fixed quickly, cause you got the debug_tables solution where it gets you the coordinates, you can write a function to retrieve the data from pdfminer.

I find this issue too in my case, but pdfminer works fine with the ordering.

**Comment by jsvine** [comment]
Cleaning up old issues. Feel free to reopen.
