### ISSUE TITLE
function "extract_words" extract words that don't exist in a pdf.

### ISSUE THREAD

**Issue by HKAFITGlitter** [jsvine/pdfplumber#1129]
## Describe the bug

*A clear and concise description of what the bug is.*
I just want to extract words in a pdf, but functions like extract_words(), extract_text(), and extract_text_line() all return some words that don't display in a pdf. 
For example, it is supposed to return "观点聚焦Investment" but "[观Ta点bl聚e_焦yem Inevie1s]. why does it return "Ta", 'bl', 'e', and 'yem Inevis 1s]'. How to remove these characters? I just want to extract words explicitly displaying in a pdf.

## Code to reproduce the problem
python code:
import pdfplumber
pdf_path = r"test.pdf"
with pdfplumber.open(pdf_path) as pdf:
    page_0 = pdf.pages[0]
    print(page_0.extract_text())

*Paste it here, or attach a Python file.*
![image](https://github.com/jsvine/pdfplumber/assets/136429622/76670185-c57d-4b74-ad4c-a38b0a159428)

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*
[test.pdf](https://github.com/jsvine/pdfplumber/files/15085488/test.pdf)

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

it is supposed to return "观点聚焦 Investment Focus"

## Actual behavior

However, it returns "[观Ta点bl聚e_焦yem Inevie1s] tment Focus".

## Screenshots

*If applicable, add screenshots to help explain your problem.*
![image](https://github.com/jsvine/pdfplumber/assets/136429622/389d3987-6899-4f96-b0b8-f740f647108a)

## Environment

- pdfplumber version: 0.10.3
- Python version: 3.10
- OS: windows

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
The issue here appears to come from overlapping character text, partly due to invisible characters on the page. The simplest solution is to lower the `y_tolerance` parameter:

<img width="667" alt="Screenshot" src="https://github.com/jsvine/pdfplumber/assets/534702/c0d3ad5b-63a5-494f-ba1c-b1fa61c21a64">

Another approach, if you wanted to remove those invisible characters that spell out `[Table_Info]` etc., would be to filter the page:

```python
def not_hidden_text(obj):
    return not (
        obj.get("non_stroking_color") == (1,)
        and obj.get("fontname") == "ABCDEE+Calibri"
    )

print(page.filter(not_hidden_text).extract_text())
```

<img width="656" alt="Screenshot" src="https://github.com/jsvine/pdfplumber/assets/534702/41ab8f03-2f79-482a-98fc-bb5fa4353a2d">

**Comment by HKAFITGlitter** [comment]
thanks!
