### ISSUE TITLE
How to extract unbounded tables from PDF files using pdfplumber?

### ISSUE THREAD

**Issue by AakashBasu** [jsvine/pdfplumber#113]
I've a requirement of extracting tables and graphs as text (csv) and images respectively from PDFs.

Till now I could achieve extracting jpgs using startmark = b"\xff\xd8" and endmark = b"\xff\xd9", but not all tables and graphs in a PDF are plain jpgs, hence my code fails badly in achieving that.

Example, I want to extract table from page 10 and graphs from page 11 as image or something which is feasible from the below given link. How to go about it?

https://hartmannazurecdn.azureedge.net/media/2800/hartmann-annual-report-2018.pdf

Used your template code:

```
import pdfplumber
pdf = pdfplumber.open(r'C:\Users\aaka\test\PDF_Extraction\hartmann-annual-report-2018.pdf')
page = pdf.pages[10]
a = page.extract_table()
print(a)
```

The variable **a** infers no table at all. What to do for these kind of tables?

**Comment by jsvine** [comment]
Hi @AakashBasu, and interesting questions. A few responses:

- Unfortunately, I haven't done much work trying to extract images from PDFs, so I don't have any particular advice on that. But it's a topic worth examining more closely.

- In the code you've provided, `page` is the *Page 11* (since Python lists are zero-indexed); there are no tables on Page 11, so I'm not surprised that `a` doesn't find any tables.

- The charts on Page 11 appear not to be images, but rather drawings composed of text and rectangles/lines. (Click-and-drag your cursor along one of the axes to see what I mean.) But you could convert the whole page to an image, using `page.to_image(...)`, and then crop to the bounding box of interest.
