### ISSUE TITLE
Bug in utils.py

### ISSUE THREAD

**Issue by jeffbarrera** [jsvine/pdfplumber#14]
When I attempt to open [this file](https://github.com/jsvine/pdfplumber/files/280288/cupertino_usd_4-6-16.pdf) using `pdfplumber.open(filepath)`, I get the following error:

```
File "/Users/Jeff/anaconda/envs/py27/lib/python2.7/site-packages/pdfplumber/utils.py", line 42, in decode_text
    if s.startswith(b'\xfe\xff'):
AttributeError: 'list' object has no attribute 'starts with'
```

Seems like a list is being passed in when a string is expected?

**Comment by jsvine** [comment]
Thanks for catching this, Jeff! I hadn't encountered this before, but that's exactly what's happening. Some metadata fields — `AAPL:Keywords` in the case of this PDF — can be represented as lists of strings, instead of single strings. I've made a hotfix, added a test, bumped the library to `v0.4.4`, and pushed the new version to PyPi. If you run `pip install --upgrade pdfplumber` and retry your script, does that fix things?

**Comment by jeffbarrera** [comment]
Yep, that works. Thanks!
