### ISSUE TITLE
Best approach for text that spans columns?

### ISSUE THREAD

**Issue by Kirkman** [jsvine/pdfplumber#16]
I'm trying pdfplumber for the first time. I really like it!

Here's my question. I deal with a lot PDFs like [this one](http://www.franklinmo.net/newdata/election/GM4_16Results.pdf). I have figured out how to get pdfplumber to identify the curved boxes, crop the page to each of those boxes, and then run extract_table() on those crops.

It's working great, with one exception. The first line (or lines) are essentially a title/header, and they span the columns of the table. So extract_table() will break the first line(s) at each column. eg:

```
[u'MERAMEC R-III SCHOOL', u'BOARD', u'MEMBER', None]
```

Is there a recommended approach for dealing with content which spans columns? Or just address it in the logic of my parser?

**Comment by jsvine** [comment]
So glad to hear it! And that's a great question. Currently, `pdfplumber` doesn't provide any special methods for handling column-spanning rows. But it's a really interesting problem to try to solve. For now, the recommended approach is just to write custom logic, as you suggest. If you run into any difficulties with that, I'd be happy to take a look at the code.

**Comment by Kirkman** [comment]
Curious if this has changed in the two years since I first asked the question. 

I still have a lot of PDFs where a header row might have text spanning multiple columns, which seems to defeat table extraction.

**Comment by jsfenfen** [comment]
@Kirkman I believe the best approach is still to write your own logic--there's so many examples of weird tables that writing a general approach gets super complicated. To my mind it's useful to write your own parser, as you can build in logical tests that detect when it is going wrong, which is the sorta feedback that's harder to convey in an automated extraction, but is often required in dealing with weird formats.

**Comment by Kirkman** [comment]
Another thought. In this specific case, is there a way to adjust the table parser settings so that it identifies the column-spanning header rows as a separate table? There is a full empty line of white space between those rows and the actual tables.

**Comment by jsvine** [comment]
Hi @Kirkman, I'm catching up on a few old issues and came back across this one. I realize you probably have moved on from this particular challenge, but for the sake of responding:

I can't think of a simple, library-generalizable approach that would provide the functionality sought. I think the best approach for tables like these (which, in some respects, depend on human spatial reasoning skills rather than explicit delineations — and are more akin to custom-structured lists than proper tables) is to write a bit of custom code. For instance, you could use `page.crop(...)` to divide the page into each candidate's section, and then parse each individually.
