### ISSUE TITLE
How can I use page.filter?

### ISSUE THREAD

**Issue by pakaLFZ** [jsvine/pdfplumber#165]
I tried to use it like this 
`new_page = page.filter(lambda page:(page["object_type"] == "line"))`
However nothing happened.
Thank you for your help!

**Comment by jsvine** [comment]
Hi, @pakaLFZ. Unfortunately, I don’t fully understand what you mean by “nothing happened”. Closing this issue for now, due to lack of specific detail, but feel free to reopen it with the following:

- An example PDF
- A short, working code snippet that demonstrates the issue
- An explanation of what you would expect to happen vs. what you observe happening
