### ISSUE TITLE
Missing edge value when using explicit vertical and horizontal lines in some cases

### ISSUE THREAD

**Issue by sjainam** [jsvine/pdfplumber#175]
I use table settings like this:
{
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines"
}
![Screenshot from 2020-01-31 18-03-29](https://user-images.githubusercontent.com/41431704/73540102-041ade00-4455-11ea-9476-235cbef26a87.png)
![Screenshot from 2020-01-31 18-16-12](https://user-images.githubusercontent.com/41431704/73540394-ce2a2980-4455-11ea-8a80-b107c247d406.png)

seen in image edge to edge line not drawn in the left side, the line is the move from the edge
and this one cut the value, I found in  .`debug_tablefinder`

**Comment by jsvine** [comment]
Interesting. It might have something to do with `pdfminer.six`'s layout engine, but it's hard to say for sure without reference to the actual PDF itself.

**Comment by sjainam** [comment]
Here is [Pdf](https://github.com/jsvine/pdfplumber/files/4142179/ErrorFIle.pdf) file. 
Result of `debug_tablefinder`
![Screenshot from 2020-02-01 11-11-05](https://user-images.githubusercontent.com/41431704/73587561-9ec1fe00-44e3-11ea-8e1c-810c4338f099.png)

**Comment by sjainam** [comment]
Here is [pdf](https://github.com/jsvine/pdfplumber/files/4142183/ErrorFIle.pdf)
And Output of `debug_tablefinde`
![Screenshot from 2020-02-01 11-15-54](https://user-images.githubusercontent.com/41431704/73587611-3d4e5f00-44e4-11ea-878a-a65b29b54e9c.png)

**Comment by jsvine** [comment]
Hi @sjainam. I took some time to look into this, and it's a tricky one! If you run this code:

```python
page = pdf.pages[0]
im = page.to_image(resolution = 300)

(
    im.reset()
    .draw_rects(page.rects, stroke = "green", stroke_width = 3, fill = None)
    .draw_lines(page.lines, stroke_width = 3)
)
```

... you can start to see what's happening:

![debug](https://user-images.githubusercontent.com/534702/74074063-96356000-49da-11ea-9eb2-42f53024a3f1.png)
 
... which is that there are, slightly inset from the `lines`, a series of `rects` in the header. Those objects come first in the PDF, and so the tablefinder uses them as a provisional starting point. Then, because `pdfplumber` wants to be tolerant of lines that are *slightly* offset from each other, it "snaps" the nearby vertical line to that x-position.

You can avoid this all by setting `snap_tolerance` to `0` in your table settings:

```python
{
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines",
    "snap_tolerance": 0,
}
```
