### ISSUE TITLE
Merge/Overlapped Text in PDF causes jumbled text

### ISSUE THREAD

**Issue by AbhishekCW** [jsvine/pdfplumber#178]
![image](https://user-images.githubusercontent.com/49337513/73820694-50c93500-4818-11ea-82b6-13f2d18d46e5.png)
In this pdf there are lines available I can able to extract tables with `tablesettings={'horizontal_strategy':'lines', 'vertical_strategy':'lines'}`. But, at this particular cell I got the jumbled data because of some rendering issue. As when when you select the text in pdf would give:

![image](https://user-images.githubusercontent.com/49337513/73820941-d6e57b80-4818-11ea-80d0-0613c67653c0.png)

Is this possible to detect this text overlap?

**Comment by jsvine** [comment]
Hi @AbhishekCW, it is very difficult to diagnose `pdfplumber` issues without the original PDF, since so much of the parsing depends on how to the PDF was created. Closing this issue for now, but feel free to reopen with the file. You might also want to try adjusting some of the other table-settings, such as `text_y_tolerance`.

**Comment by AbhishekCW** [comment]
Hi @jsvine . Thanks for your reply. I have tried with table-settings what you have mentioned. But still it does not separate the texts appeared on the same co-ordinates. Here is the file on what I am working.
[edited.pdf](https://github.com/jsvine/pdfplumber/files/4179057/edited.pdf)
