### ISSUE TITLE
How to parse this format ?

### ISSUE THREAD

**Issue by Lucipher** [jsvine/pdfplumber#189]
How to parse this format , it could not extract the table 

![image](https://user-images.githubusercontent.com/1323545/75939877-7e140c00-5ec6-11ea-9957-f4342ef2a9d5.png)

[PDF File](http://www.klineglobalroro.com/schedules/3-1_north_america_to_asia_australia_express(nax).pdf)

**Comment by jsvine** [comment]
Hi @Lucipher, that's a strange one. It seems that many of the lines aren't being identified as PDF objects. I don't have an immediate solution to this, but will try to spend more time looking into it.

**Comment by jsvine** [comment]
Apologies for the delay on this; I'm going through old repository issues. The good news is that, in the time since you posted this, whatever underlying problems there were seem to have been fixed. 

Running `page.to_image().debug_tablefinder()` produces this:

![image](https://user-images.githubusercontent.com/534702/180091627-db0376b5-c74e-4f6b-b354-c23448c40e95.png)
