### ISSUE TITLE
bbox inversion

### ISSUE THREAD

**Issue by ubmarco** [jsvine/pdfplumber#198]
Hi,
this issue is about better understanding pdfplumber's bounding box (bbox) definition.
README.md states the following bbox definition `(x0, top, x1, bottom)`.
I'm confused why the bbox definition is not `(x0, y0, x1, y1)`.

I spent a lot of time understanding where my visual debugging issues came from and I'm not sure if all below considerations are correct, please tell me when I'm wrong.

This is the definition of each coordinate:
```
x0      Distance of left side of object from left side of page.
x1      Distance of right side of object from left side of page.
y0      Distance of bottom of object from bottom of page.
y1      Distance of top of object from bottom of page.
top     Distance of top of object from top of page.
bottom  Distance of bottom of the object from top of page.
```
As I'm having continuous confusion with this, I painted some ASCII art to enable a discussion:
```
PDF standard and pdfminer bbox               pdfplumber bbox                
*-page------------------------*              *-page------------------------*
|                             |              |                ^      ^     |
|                             |              |               top     |     |
|                             |              |                v      |     |
|        +-bbox----+          |              |        +-bbox----+    |     |
|<--x0-->|         |    ^     |              |<--x0-->|         |    |     |
|        |         |    |     |              |        |         |  bottom  |
|<-------|---x1--->|    |     |              |<-------|---x1--->|    |     |
|        +---------+    |     |              |        +---------+    v     |
|            ^          |     |              |                             |
|           y0         y1     |              |                             |
|            v          v     |              |                             |
*-----------------------------*              *-----------------------------*
```
The left is how pdfminer handles bbox for objects. The PDF standard defines the coordinate system origin of pages as the bottom left corner, so pdfminer complies with that.
The left is how pdfplumber handles bboxes.

I wanna have one definition of a bounding box which means I have to write conversion code around pdfplumber which I don't like. Any opinions on that?

**Comment by jsvine** [comment]
Hi @ubmarco, and thank you for the question. It's a good one, with an explanation that's worth documenting here. These are some of the reasons I chose to use a coordinate system with the origin (`0, 0`) in the top-left corner, rather than the bottom-left corner:

- People read PDFs, generally speaking, from the top-left toward the bottom-right. Although it is contrary to the PDF standard, placing the origin in the top-left felt more intuitive to me and, I guessed, to newcomers.

- Similarly, when processing multiple pages of a PDF, I wanted to be able to distinguish between objects at similar `y` coordinates but on different pages. The total distance from the very top of the PDF (`doctop`) seemed like the natural way to measure this; it seemed reasonable, then, to have `top` be one of the the primary `y` coordinates, and for it also to be measured from the top of a page.

- Although I agree that it's a good goal to stay consistent with the PDF specification, many (perhaps most?) other common visual layout systems use an origin in the top-left corner, e.g., SVG, Canvas, ImageMagick, PIL/Pillow (which PDFPlumber uses for visual debugging), et cetera.

**Comment by ubmarco** [comment]
Hi @jsvine,

thanks for the quick reply. That looks religious to me, so it's maybe not reasonable to start a discussion. Also, any change in this will not be backwards compatible and break many existing pdfplumber integrations, so I wouldn't change anything here.  However, for the record, I still like to point out the problems that I'm seeing.

* pdfplumber is a library not an application. As a library it's quite unknown what users will do with it because the library will be part of all sorts of applications. I see pdfminer and also pdfplumber mainly in the PDF domain, so sticking with PDF would be a natural decision for me.
* In my case I need to interact with both pdfplumber and pdfminer. pdfplumber gets me the tables with an awesome stability and detection rate (far better than camelot with lattice flavor and its defaults for many of my PDFs). However I need pdfminer for text layout analysis, named destinations and link annotations which is not fully available in pdfplumber. So I have to deal with various coordinate systems which confuses me a lot and needs to be wrapped.

I however also understand your rationale and decision and appreciate the efforts your put into the library, so I'll close the issue and say thanks for your help.

**Comment by jsvine** [comment]
Thanks for the explanation, @ubmarco! I really appreciate your thoughtful and clear comments. To be honest, when I was initially building PDFPlumber, I hadn't considered that someone might use it *in combination with* `pdfminer`. Perhaps, if I were beginning from scratch, I'd stick to their coordinate system. 

Are there particular parts of `pdfminer`'s text layout analysis, named destinations, and link annotations that you think would be useful/possible to incorporate into PDFPlumber? If so, I'd be open to considering them as new features.
