### ISSUE TITLE
metadata parse bug & bbox decimalize bug

### ISSUE THREAD

**Issue by meldonization** [jsvine/pdfplumber#203]
> pdf = pdfplumber.open('metadata_bug.pdf')
```
Traceback (most recent call last):
  File "<input>", line 11, in <module>
  File ".venv/lib/python3.6/site-packages/pdfplumber/utils.py", line 82, in decode_text
    return ''.join(PDFDocEncoding[o] for o in ords)
  File ".venv/lib/python3.6/site-packages/pdfplumber/utils.py", line 82, in <genexpr>
    return ''.join(PDFDocEncoding[o] for o in ords)
  File ".venv/lib/python3.6/site-packages/pdfplumber/utils.py", line 81, in <genexpr>
    ords = (ord(c) if type(c) == str else c for c in s)
TypeError: ord() expected a character, but string of length 4 found
```

pdf: [metadata_bug.pdf](https://github.com/jsvine/pdfplumber/files/4514320/metadata_bug.pdf)

> pdf = pdfplumber.open('metadata_bug.pdf')
> pdf.pages[0].objects
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".venv/lib/python3.6/site-packages/pdfplumber/page.py", line 66, in objects
    self._objects = self.parse_objects()
  File ".venv/lib/python3.6/site-packages/pdfplumber/page.py", line 155, in parse_objects
    process_object(obj)
  File ".venv/lib/python3.6/site-packages/pdfplumber/page.py", line 152, in process_object
    process_object(child)
  File ".venv/lib/python3.6/site-packages/pdfplumber/page.py", line 128, in process_object
    for k, v in obj.__dict__.items()
  File ".venv/lib/python3.6/site-packages/pdfplumber/page.py", line 129, in <genexpr>
    if k in CONVERSIONS_KEYS)
  File ".venv/lib/python3.6/site-packages/pdfplumber/page.py", line 47, in decimalize
    return utils.decimalize(x, self.pdf.precision)
  File ".venv/lib/python3.6/site-packages/pdfplumber/utils.py", line 115, in decimalize
    return type(v)(decimalize(x, q) for x in v)
  File ".venv/lib/python3.6/site-packages/pdfplumber/utils.py", line 115, in <genexpr>
    return type(v)(decimalize(x, q) for x in v)
  File ".venv/lib/python3.6/site-packages/pdfplumber/utils.py", line 117, in decimalize
    return _decimalize(v, q)
  File ".venv/lib/python3.6/site-packages/pdfplumber/utils.py", line 110, in _decimalize
    raise ValueError("Cannot convert {0} to Decimal.".format(v))
ValueError: Cannot convert <PDFObjRef:29> to Decimal.
```

pdf: [decimalize_bug.pdf](https://github.com/jsvine/pdfplumber/files/4514322/decimalize_bug.pdf)

**Comment by meldonization** [comment]
see fix in pull request #204 
Many thanks

**Comment by jsvine** [comment]
He @meldonization, and thanks again for raising this issue. There are two very distinct things happening with these bugs.

##  decimalize_bug.pdf

This ended up being a problem with `pdfminer.six`'s `.resolve_all(...)` method, which was unprepared to handle tuples. In https://github.com/jsvine/pdfplumber/commit/85f422d0012aef2e06b726fe1d8da7da3c14de33, I've fixed that by writing our own version of that method and added a test for your PDF. It seems to work.

## metadata_bug.pdf

This one is trickier. The problem seems to stem from a corruption or bug in the PDF itself, in which it seems to combine the [`/Info` and `/Root` trailer objects](https://www.oreilly.com/library/view/pdf-explained/9781449321581/ch04.html). Here's the trailer:

<img width="154" alt="Screen Shot 2020-04-29 at 8 19 05 AM" src="https://user-images.githubusercontent.com/534702/80602919-bbe06d00-89fd-11ea-86b8-e824a8051282.png">

Note that both `/Info` and `/Root` point to PDF object reference `8`. Looking at that object, and the ones it references:

<img width="452" alt="Screen Shot 2020-04-29 at 8 19 43 AM" src="https://user-images.githubusercontent.com/534702/80603016-dca8c280-89fd-11ea-81aa-7bb105bbe6a2.png">

... you can see the mixing-up. (The first two lines of the object seem to belong to the `/Root` catalog and the third to the `Info` metadata dictionary.) The error you get comes when pdfplumber tries to interpret `/Pages 3 0 R` as metadata ... when in reality it is part of the `/Root` document catalog. 

For now, this seems like an extreme edge case — I haven't seen it crop up anywhere else, and PDF files generally should not have this problem. Although your PR in https://github.com/jsvine/pdfplumber/pull/204 does indeed resolve the error, I worry that it overfits to this particular PDF and may have unforeseen side-effects down the road.

That said, I very much appreciate you raising the issue. This will be a handy reference if other people encounter similar errors in the future.

In the meantime, this particular PDF can be "fixed" either by removing the `/Info 8 0 R` line at the end of the file, or (if you want to retain the metadata), moving the `/CreationDate(D:20191231093555+08'00') [...]` line to a new PDF object and changing `/Info 8 0 R` to reference it in the trailer.

**Comment by meldonization** [comment]
Hi @jsvine thank you for explain these two pdf cases in detail. I totally understand the situation when pdfminer can't resolve the object in the right way. 

For the extreme cases that I encountered among tons of PDFs, a possible better way would be customizing my special version of pdfplumber to deal with these files. Deleting or changing lines in PDF files would be hazardous because that will change the hash key of the file.... Still It would be nice to handle these errors in a proper way within the code itself. Thanks again for your reply.
