### ISSUE TITLE
How to get char bboxes associated to output of extract_text?

### ISSUE THREAD

**Issue by FelipeAdachi** [jsvine/pdfplumber#215]
Hello!

I would like to get a string using the extract_text() function, but I also need the position information on a character level of the string, or at least on a word level. I am aware the extract_words() has bbox information, but the organization by lines given by extract_text() is also important to me.

How would I go about implementing this? I tried aligning each char of the string obtained from extract_text() with the .chars objects, but they don't necessarily follow the same order.

Any ideas? Or perhaps it isn't possible?

**Comment by jsvine** [comment]
Hi @FelipeAdachi, and thanks for your interest in this library. Unfortunately, I don't think there's a simple, immediately-available solution to achieve what you're looking for, but you could modify `.extract_text()` so that it returns the full object description of each char object, instead of the concatenated string.
