### ISSUE TITLE
Missing first and last column for borderless tables

### ISSUE THREAD

**Issue by amansani** [jsvine/pdfplumber#223]
[Testing.pdf](https://github.com/jsvine/pdfplumber/files/4806619/Testing.pdf)

Below is the code snippet i used in jupyter visual debugging tool. Missing first and last column data due to no borders at both the ends. 

Any help is really appreciated. Thank you.

import pdfplumber
import pandas as pd
import decimal

pdf = pdfplumber.open("useAttacedPDFFile")
testingPage = pdf.pages[0]

im = testingPage.to_image()
im
"
![Image1](https://user-images.githubusercontent.com/31453971/85178557-c6c0bc80-b24c-11ea-8944-fd28f73d74f1.PNG)

table_settings = {
        "vertical_strategy": "lines", "horizontal_strategy": "lines",
        "snap_tolerance": decimal.Decimal(10), "join_tolerance": decimal.Decimal(700)}

table = testingPage.extract_table(table_settings)

table[:3]

![Image2](https://user-images.githubusercontent.com/31453971/85178636-ff609600-b24c-11ea-8239-37e85e037757.PNG)

df = pd.DataFrame(table[1:], columns=table[0])
df

im.debug_tablefinder(table_settings)

![Image3](https://user-images.githubusercontent.com/31453971/85178731-43ec3180-b24d-11ea-8ae3-49dd789ae5b7.PNG)
"

**Comment by jsfenfen** [comment]
Hi @amansani, the table extraction settings allow you to change how tables are read. 

https://github.com/jsvine/pdfplumber#table-extraction-settings

Have you tried "vertical-strategy" being "text"? Not sure it'll fix it, but the idea is that it tries to identify cells by text location, rather than lines. You can also use "explicit" to give it a list of breaks. If you have many pages to do this for, you might want to identify where the explicitly-assigned breaks should be detecting the location of the column headers, but that would be more work.

**Comment by amansani** [comment]
Hello Jacob, thank you for your quick response.

I have more than 80 tables in one pdf page, explicit might not work in my case. Also i have n number of pdf files to retrieve different variety of tables. 

Tried with vertical-strategy to text, able to get first and last column but has an impact on missing few header portion and the last right column data

table_settings = {
        "vertical_strategy": "text", "horizontal_strategy": "lines",
        "snap_tolerance": decimal.Decimal(3), "join_tolerance": decimal.Decimal(700)}

![Image4](https://user-images.githubusercontent.com/31453971/85181176-4487c680-b253-11ea-99b5-02171bea10ce.PNG)

**Comment by jsfenfen** [comment]
You may wanna also look at setting "keep_blank_chars": True. 

Apologies if I wasn't clear about the explicit strategy. Here's a lengthier take on it. 
- Find a column that parses correctly. As you've applied it above, the first column generates the correct breaks. Figure out what those are, and apply them explicitly to the other columns.
- If that alone doesn't work, and you're still getting erroneous breaks in the other dimension, do the same thing--identify a row that has the correct breaks and apply them elsewhere.  

Here's a massively ugly example: https://github.com/jsfenfen/pdf20/blob/master/pdfs/senate_expenditures.ipynb 

Having lotsa pages shouldn't matter, you need to focus on finding "anchor words" or other features that delineate the regions you need. This takes some creativity--it's hard to see from here how consistent pages are--but essentially that means identifying regions *in reference to text on them*. 

For simple tables like this, that's likely all you need. But for more complicated stuff it's normal to use a combination of individual word locations in concert with tablefinder, or just word locations alone, as tablefinder's opinion can sometimes be unhelpful.

**Comment by amansani** [comment]
Thanks for the inputs Jacob, I am gonna try it today.

**Comment by jsvine** [comment]
Hi @amansani and thanks @jsfenfen. From a quick glance, it looks like what was happening initially is that the table has no actual lines closing the leftmost and rightmost columns. There are a few ways you could resolve this (including Jacob's suggestion), but here's the one I would personally use if this were my code:

- On each page, find the first wide horizontal line, and note its `x0` and `x1`
- Use those values in table_settings, as explicit vertical line positions.

So that'd look something like this (though I haven't tested the code):

```python
import pdfplumber
pdf = pdfplumber.open("file.pdf")

def parse_page(page):
    h_lines = [ line for line in page.lines if line["width"] > 300 ]
    if len(h_lines) == 0:
        return None
    return page.extract_table({
        "vertical_strategy": "lines", 
        "horizontal_strategy": "lines",
        "explicit_vertical_lines": [ h_lines[0]["x0"], h_lines[0]["x1"],
        "snap_tolerance": 10
    })

all_tables = list(map(parse_page, pdf.pages))
```

Note that this approach makes two assumptions:

- It assumes that all tables follow the same general style
- It assumes that there is at most one table per page

If either of those assumptions are incorrect, this approach would need to be tweaked.

**Comment by amansani** [comment]
Hello @jsvine . Thanks for the inputs. 

In my case the two assumptions which you listed does not apply. All the tables not have the same general style and the table might not exists in each page.

**Comment by jsvine** [comment]
> the table might not exists in each page.

This should be no problem; the code above would handle that. The only problem would be if there are multiple tables per page, in which case you'd need to add logic to handle that.

> All the tables not have the same general style

This, however, would be a problem. If the styles have a very wide variety, then `pdfplumber` might not be the ideal tool for this project.
