### ISSUE TITLE
Beyond the line can't identify

### ISSUE THREAD

**Issue by andlike** [jsvine/pdfplumber#230]
[Sn石墨炉20-1010-2气.pdf1(1).pdf](https://github.com/jsvine/pdfplumber/files/4895713/Sn.20-1010-2.pdf1.1.pdf)
![image](https://user-images.githubusercontent.com/9100593/87021124-63043080-c207-11ea-9102-a787ae13399d.png)
methods:   page.extract_text()

result:
![image](https://user-images.githubusercontent.com/9100593/87021594-fdfd0a80-c207-11ea-9314-44248f77d45b.png)

**Comment by jsvine** [comment]
Hi @andlike, and thanks for your interest in this library. I have examined the PDF (thank you for sharing it) and it seems that the problem is *not* with the lines, although I can understand why it might have seemed that way at first. Instead, the issue seems to be that those particular sections of text are not being identified as characters. To demonstrate:

```python
pdf = pdfplumber.open("Sn.20-1010-2.pdf1.1.pdf")
page = pdf.pages[0]
im = page.to_image()
im.reset().draw_rects(page.chars) # Draw a rectangle around all `char` objects
```

Produces this:

![image](https://user-images.githubusercontent.com/534702/87854886-e6e2aa80-c8e2-11ea-85d6-0374fc6fd585.png)

It's possible that it's a problem with the PDF itself, or possible a quirk in how `pdfminer.six` processes the PDF; either way, I unfortunately do not think it can be resolved through `pdflumber`. You might want to check with the maintainers at https://github.com/pdfminer/pdfminer.six

Best, and thanks again,
Jeremy

**Comment by StarMagicAI** [comment]
@jsvine thanks
