### ISSUE TITLE
Removal of some bboxes

### ISSUE THREAD

**Issue by harinadh12** [jsvine/pdfplumber#235]
How can i remove a a bbox  from table after the table is identified. I dont want to get the below bbox as a column, can i remove it from table extraction.

**Comment by harinadh12** [comment]
![image](https://user-images.githubusercontent.com/68689504/88276827-526eb280-ccfd-11ea-8354-13dfcf5b1526.png)

**Comment by harinadh12** [comment]
![image](https://user-images.githubusercontent.com/68689504/88277136-d88af900-ccfd-11ea-8710-a5d295ad8d62.png)

**Comment by samkit-jain** [comment]
You can try and use `snap_tolerance` in this case. More details [here](https://github.com/jsvine/pdfplumber#table-extraction-settings).

**Comment by jsvine** [comment]
Thanks for answering, @samkit-jain! I think that's a good suggestion — and typically what I do when I encounter tables like that.

**Comment by hariappi** [comment]
> You can try and use `snap_tolerance` in this case. More details [here](https://github.com/jsvine/pdfplumber#table-extraction-settings).

Thanks for your reply. Is there any way to automatically adjust the table_settings based on the pdf as adjusting the settings for wide variety of pdf's is not possible. its just a curious question.

**Comment by jsvine** [comment]
Hi @harinadh12, and it's a very good question. Currently, this is not possible, as pdfplumber tries to be as explicit/direct as possible and contain as little "magic" as possible. FWIW: Longer term, I'm hoping to refactor pdfplumber's table-finding logic to be more modular, so that people can choose from (and mix) a broad range of strategies and approaches — and easily develop new ones (including, perhaps, those that do more auto-adjustments).

In the meantime, [Camelot](https://camelot-py.readthedocs.io/en/master/) might provide more of the approach you are seeking.

**Comment by hariappi** [comment]
> Hi @harinadh12, and it's a very good question. Currently, this is not possible, as pdfplumber tries to be as explicit/direct as possible and contain as little "magic" as possible. FWIW: Longer term, I'm hoping to refactor pdfplumber's table-finding logic to be more modular, so that people can choose from (and mix) a broad range of strategies and approaches — and easily develop new ones (including, perhaps, those that do more auto-adjustments).
> 
> In the meantime, [Camelot](https://camelot-py.readthedocs.io/en/master/) might provide more of the approach you are seeking.

Thanks @jsvine for your elaborate explanation.
