### ISSUE TITLE
Text parsing error for a column occupying more than one row

### ISSUE THREAD

**Issue by wuliKingQin** [jsvine/pdfplumber#259]
Can you provide a public method to solve the problem of a column occupying more than one row? Or offer a solution
![1598458784890](https://user-images.githubusercontent.com/23000059/91329713-10a0c280-e7fb-11ea-89ec-6e9224c7325b.jpg)

**Comment by wuliKingQin** [comment]
![image](https://user-images.githubusercontent.com/23000059/91330623-47c3a380-e7fc-11ea-87b9-2d33c5c6427a.png)

As shown in the figure, after parsing, the newline text is put on another line, which is not easy to deal with, I hope you can provide some solutions, thank you very much!

**Comment by samkit-jain** [comment]
Hi @CuteyBoy Thanks for your interest in the library. Could you please provide more details on what you are trying to achieve and what all you have tried? 

To me, it looks like you want to extract the text in the table row by row handling multiline lines in a cell (because the output screenshot you have shared in https://github.com/jsvine/pdfplumber/issues/259#issuecomment-680988579 looks like the output of `.extract_text()`). Assuming that is indeed the case, you can try doing this:
```python
# Load the library.
import pdfplumber

# Load the PDF.
pdf = pdfplumber.open("file.pdf")

# Get the first page.
p0 = pdf.pages[0]

# Table has line separators.
ts = {
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines",
}

# Extract the table.
table = p0.extract_table(table_settings=ts)

# Iterate over all the rows.
for row in table:
    # Print the rows one by one handling multiline content.
    print(" ".join([cell.replace("\n", "") for cell in row]))
```

If table is like

| COLUMN 1 | COLUMN 2 |
|---------|---------|
| my multiline <br/> cell | single line cell |

the output would be

```
COLUMN 1 COLUMN 2
my multiline cell single line cell
```

Again, this is based on my assumption and it would be great if you could provide more details along with the PDF.

**Comment by wuliKingQin** [comment]
If you use the extract_table() method, the table cannot be found, so I use the extract_text() method. This method can always get the content I want, and then filter it myself, but when I use the extract_text() method , Found that there are two problems:
1. If a line breaks in the cell, the content read is the same as the comment above;
[error_dpf_1.pdf](https://github.com/jsvine/pdfplumber/files/5135140/error_dpf_1.pdf)

2. If the line breaks in the cell and the part of the line break is hidden, the read data will result in mixed output with the content 
in the cell below.
[error_dpf_2.pdf](https://github.com/jsvine/pdfplumber/files/5135143/error_dpf_2.pdf)

**Comment by wuliKingQin** [comment]
![error](https://user-images.githubusercontent.com/23000059/91418580-e85da600-e884-11ea-8277-e81da263b431.png)

This is a graph with hidden parts and parsing errors

**Comment by samkit-jain** [comment]
For first PDF
I am able to extract the tables (using the table settings I had shared in my earlier comment) just fine. Below is the visual debugger output (cropped)
![image](https://user-images.githubusercontent.com/15127115/91443298-c538f380-e890-11ea-91ba-696216762968.png)
and this is the tabular output
```
['项目', '2019年12月31日', '2018年12月31日']
['流动资产：', '', '']
['货币资金', '603,254,466.37', '201,524,986.35']
['结算备付金', '', '']
['拆出资金', '', '']
['交易性金融资产', '', '']
['以公允价值计量且其变动计入当', '', '']
[None, '', '']
['期损益的金融资产', None, None]
[None, '', '']
['衍生金融资产', '', '']
['应收票据', '51,775,620.00', '37,842,464.00']
['应收账款', '264,287,482.38', '305,446,276.85']
['应收款项融资', '4,770,000.00', '']
['预付款项', '506,537,165.36', '546,727,778.86']
['应收保费', '', '']
['应收分保账款', '', '']
['应收分保合同准备金', '', '']
['其他应收款', '451,475,592.29', '910,951,276.48']
['其中：应收利息', '', '']
['应收股利', '', '']
['买入返售金融资产', '', '']
['存货', '151,361,220.79', '963,715,952.70']
['合同资产', '', '']
['持有待售资产', '', '']
['一年内到期的非流动资产', '', '']
['其他流动资产', '12,600,866.73', '10,316,317.01']
['流动资产合计', '2,046,062,413.92', '2,976,525,052.25']
['非流动资产：', '', '']
```

In the 7th row, you can see that it has been split into 2 lines because there are some hidden lines and you would need to handle this in a post processing step. Something like this might help.
```python
new_table = []  # This is the new table.

for row in table:
    if None in row:  # If any of the cell is None, join the row with the last row in the new table.
        new_table[-1] = [f"{cell1 if cell1 is not None else ''}{cell2 if cell2 is not None else ''}".strip() for cell1, cell2 in zip(new_table[-1], row)]
    else:
        new_table.append(row)

# Print the new table row wise.
for row in new_table:
    print(row)
```

This gives the output as 
```
['项目', '2019年12月31日', '2018年12月31日']
['流动资产：', '', '']
['货币资金', '603,254,466.37', '201,524,986.35']
['结算备付金', '', '']
['拆出资金', '', '']
['交易性金融资产', '', '']
['以公允价值计量且其变动计入当期损益的金融资产', '', '']
['衍生金融资产', '', '']
['应收票据', '51,775,620.00', '37,842,464.00']
['应收账款', '264,287,482.38', '305,446,276.85']
['应收款项融资', '4,770,000.00', '']
['预付款项', '506,537,165.36', '546,727,778.86']
['应收保费', '', '']
['应收分保账款', '', '']
['应收分保合同准备金', '', '']
['其他应收款', '451,475,592.29', '910,951,276.48']
['其中：应收利息', '', '']
['应收股利', '', '']
['买入返售金融资产', '', '']
['存货', '151,361,220.79', '963,715,952.70']
['合同资产', '', '']
['持有待售资产', '', '']
['一年内到期的非流动资产', '', '']
['其他流动资产', '12,600,866.73', '10,316,317.01']
['流动资产合计', '2,046,062,413.92', '2,976,525,052.25']
['非流动资产：', '', '']
```

**Comment by samkit-jain** [comment]
For the second PDF, I am able to extract tabular data just fine without any post processing adjustments using the lines-lines tables settings.
```json
{
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines"
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/15127115/91446297-eac7fc00-e894-11ea-864b-9d1ca009153f.png)

Output:
```
['买入返售金融资产', '', '', '']
['存货', '152,289,974.93', '152,289,974.93', '']
['合同资产', '', '', '']
['持有待售资产', '', '', '']
['一年内到期的非流动资产', '', '', '']
['其他流动资产', '49,460,103.90', '49,460,103.90', '']
['流动资产合计', '2,870,929,171.71', '2,870,929,171.71', '']
['非流动资产：', '', '', '']
['发放贷款和垫款', '', '', '']
['债权投资', '', '', '']
['可供出售金融资产', '183,078,602.55', '', '-183,078,602.55']
['其他债权投资', '', '', '']
['持有至到期投资', '', '', '']
['长期应收款', '', '', '']
['长期股权投资', '343,705,947.81', '343,705,947.81', '']
['其他权益工具投资', '', '', '']
['其他非流动金融资产', '', '', '139,778,044.68']
['投资性房地产', '28,174,551.88', '28,174,551.88', '']
['固定资产', '718,788,449.73', '718,788,449.73', '']
['在建工程', '512,053,425.86', '512,053,425.86', '']
['生产性生物资产', '', '', '']
['油气资产', '', '', '']
['使用权资产', '', '', '']
['无形资产', '646,471,976.73', '646,471,976.73', '']
['开发支出', '', '', '']
['商誉', '1,926,954,188.44', '1,926,954,188.44', '']
['长期待摊费用', '396,591,976.71', '396,591,976.71', '']
['递延所得税资产', '85,606,770.07', '85,606,770.07', '']
['其他非流动资产', '561,815,247.11', '561,815,247.11', '']
['非流动资产合计', '5,403,241,136.89', '5,359,940,579.02', '-43,300,557.87']
['资产总计', '8,274,170,308.60', '8,230,869,750.73', '-43,300,557.87']
['流动负债：', '', '', '']
['短期借款', '1,310,800,000.00', '1,310,800,000.00', '']
['向中央银行借款', '', '', '']
['拆入资金', '', '', '']
['交易性金融负债', '', '', '']
['以公允价值计量且其变动计入当期', '', '', '']
['损  益  的衍金生融金负融债负债', '', '', '']
['应付票据', '563,607,500.00', '563,607,500.00', '']
['应付账款', '507,038,707.03', '507,038,707.03', '']
['预收款项', '38,139,979.97', '38,139,979.97', '']
```

The cell you highlighted in https://github.com/jsvine/pdfplumber/issues/259#issuecomment-681807591 seems to contain more data than what is visible in the PDF. That is because the PDF contains hidden text as you can see from this screenshot when I try and select the text in the PDF.
![image](https://user-images.githubusercontent.com/15127115/91446834-95401f00-e895-11ea-8d9c-08ca3e43375f.png)

If you **don't** want that hidden text to be extracted, I don't think that is possible currently.

**Comment by wuliKingQin** [comment]
Thank you very much for your excellent answer, it may be that I have a problem with my strategy, I should use the `extract_table()` method for most of the tables, some special PDFS use the `extract_text ()` method for the table! Thank you very much!

**Comment by xv44586** [comment]
hi, I used code that you shared upon, but the sencond line still splited, I wonder is there a way to make the three "line" together cause they are in one cell?

[Group.pdf](https://github.com/jsvine/pdfplumber/files/5266206/Group.pdf)
![issue](https://user-images.githubusercontent.com/16846988/93978815-1912fb80-fdaf-11ea-94f1-4f6ce8781c2e.png)
result:
```python
Group Item1 A

Item2 C D F

groupItem 1.  First line First line First line First line First line First line First line;

2.  Second line Second line Second line Second line Second line

Second line Second line Second line；

3.  Third line Third line；
```

**Comment by samkit-jain** [comment]
Hi @xv44586 Thanks for sharing the PDF. Could you please share what you expect the output to be? If I use the table settings as
```json
{
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines",
    "snap_tolerance": 10
}
```
The table is detected as 
![image](https://user-images.githubusercontent.com/15127115/93988182-0cd67080-fda6-11ea-96f4-f09a3ef9db47.png)
with the data being
```
['Gr\nou\np', 'Item1', 'A', None, None]
[None, 'Item2', 'C', 'D', 'F']
[None, 'groupIte\nm', '1.  First line First line First line First line First line First line First line; \n2.  Second line Second line Second line Second line Second line \nSecond line Second line Second line； \n3.  Third line Third line；', None, None]
```
which seems correct to me.

**Comment by xv44586** [comment]
@samkit-jain Thanks for reply! I tried again, I found I losed the <code>snap_tolerance</code> ,so the result of last cell is splited into multi rows, now everything is fine. Thanks again!
