### ISSUE TITLE
extract_text() from pages should not extract data within tables

### ISSUE THREAD

**Issue by lfcbenson** [jsvine/pdfplumber#313]
extract_text() method for pages extracts all text including those from tables. Since there is a separate extract() method to extract data from a table the the extract_text() method for a Page should only extract NON - TABULAR data.

**Comment by samkit-jain** [comment]
Hi @lfcbenson and thanks for the feedback. This functionality is not natively supported but can be achieved using some filtering as also discussed in https://github.com/jsvine/pdfplumber/issues/242.

`extract_text()` works on a page object and hence, it extracts text on the whole page as that is also what one would expect. On your suggestion, I would prefer adding a new `exclude_tables` parameter that when set to `True` would return only non-tabular text instead of modifying the method to only return non-tabular text. Yes, it is possible to add support for this functionality by implementing something similar to https://github.com/jsvine/pdfplumber/issues/242#issuecomment-668448246, but, I don't think it is the best idea. With table extraction, users get more control. They get to decide what tables to keep. They get to decide what constitutes a table. Some may say that there is no table on the first page of [this PDF](https://github.com/jsvine/pdfplumber/blob/stable/tests/pdfs/federal-register-2020-17221.pdf) while some may say there is. A table of 3 columns and 1 row (or multiple rows if we consider each line of text to be a valid aligned row). The library does provide that control via the `table_settings` parameter, but, there are cases when even that is not enough. The user might need page cropping, object filtering, pre/post-processing among other things. And providing such flexibility to a method that simply extracts text will only make it more complex and difficult to use.

I am closing this issue because a workable solution to your feature request is available. But, I would love to know your thoughts on what I have shared above and take the discussion forward.

**Comment by jsvine** [comment]
Thanks @samkit-jain, I think that's exactly right.

**Comment by lfcbenson** [comment]
@samkit-jain , I think the solution you mentioned about adding an exclude_tables parameter to the extract_text() function would be great if you could implement that. That way users will have more control on which data they want to extract.
