### ISSUE TITLE
Table detected on page with no visible tables

### ISSUE THREAD

**Issue by ivoytov** [jsvine/pdfplumber#326]
## What code are you using to do it?

```
table_settings = {
   "vertical_strategy":   "lines",
  "horizontal_strategy": "lines",
   "intersection_x_tolerance": None,
  "intersection_y_tolerance": None,
  "edge_min_length":  50,
}
pdf.pages[page].to_image().debug_tablefinder(table_settings).save(f'page{page}.png')
```

## PDF file

[p_ursa10_pg9.pdf](https://github.com/jsvine/pdfplumber/files/5653431/p_ursa10_pg9.pdf)

## Expected behavior

No table should be identified on this page.

## Actual behavior

A table is identified on the page. All other pages in this long document are processed correctly.

## Screenshots

(url
![page9](https://user-images.githubusercontent.com/1527583/101366573-19317c00-3873-11eb-9d35-05c61dce2465.png)

## Environment
pdfminer.six==20200517
pdfplumber==0.5.24
Python 3.9.0
Mac OS

## Additional context

I've tried messing with other table_settings parameters but nothing so far has fixed this issue. 
Tried switching to "text" strategy but this breaks every page in the same document.

**Comment by samkit-jain** [comment]
Hi @ivoytov Appreciate your interest in the library. The table is getting identified because those lines are hidden. To filter out hidden `rect` objects from the page, you may refer to the code used in https://github.com/jsvine/pdfplumber/issues/311#issuecomment-726958591 I ran it locally and no table was extracted.

I am closing this issue. Feel free to reopen if you have any further queries.

**Comment by ivoytov** [comment]
Thanks Samkit
