### ISSUE TITLE
Can't find the last column of table

### ISSUE THREAD

**Issue by shizidushu** [jsvine/pdfplumber#330]
## What are you trying to do?
The PDF contains country and its city/postal code. I want to get the country and its city name as a pair and country and its postal code as another pair.

## What code are you using to do it?
```
import pdfplumber
import numpy as np
import pandas as pd
import re
from decimal import Decimal
import time

pdf_file = "Zipcodes_OPA_ODA-FEDEX.pdf" 
pdf = pdfplumber.open(pdf_file)
first_page = pdf.pages[0]
box = (Decimal('50.760'), Decimal('138.0'), Decimal('560.6'), Decimal('747.60'))
cropped_page = first_page.crop(bbox=(box))
im = cropped_page.to_image(resolution=150)
tf = {
        "vertical_strategy": "lines_strict",
        "horizontal_strategy": "text",
    }
im.debug_tablefinder(tf)
table = cropped_page.extract_table(tf)
table
```

## PDF file

[Zipcodes_OPA_ODA-FEDEX.pdf](https://github.com/jsvine/pdfplumber/files/5769963/Zipcodes_OPA_ODA-FEDEX.pdf)

## Expected behavior

I want to get all columns.

## Actual behavior

The last column didn't show

## Screenshots

![debug](https://user-images.githubusercontent.com/13694980/103644087-c097f080-4f90-11eb-8687-fb6a5fa266ec.png)

## Environment

- pdfplumber version: 0.5.25
- Python version: 3.6.9
- OS: Ubuntu 18.04

**Comment by samkit-jain** [comment]
Hi @shizidushu Appreciate your interest in the library. As you might have seen in the screenshot that there is a large gap between where the horizontal line ends and the vertical line starts
![image](https://user-images.githubusercontent.com/15127115/103647221-f0d79300-4f80-11eb-9083-6620776a759d.png)
To intersect these lines so that form a cell, you can use the `intersection_tolerance` key in the table settings.

In your case, the table settings would become
```json
{
    "vertical_strategy": "lines_strict",
    "horizontal_strategy": "text",
    "intersection_x_tolerance": 13
}
```

It captures the table correctly as seen in the screenshot
![image](https://user-images.githubusercontent.com/15127115/103647400-401dc380-4f81-11eb-99dd-ba895657a1cd.png)

PS: You can find the full list of supported table settings parameters [here](https://github.com/jsvine/pdfplumber#table-extraction-settings).
