### ISSUE TITLE
Rect edges can't be extracted correctly from some pdf

### ISSUE THREAD

**Issue by jackstraws** [jsvine/pdfplumber#343]
## Describe the bug

*When i prepare to extract the tables in some pdf, i find that the tables rect edges or lines can't be extracted, but the tool ``camelot`` can find these lines in same pdf*

### the 1st pdf:
[err_test1.pdf](https://github.com/jsvine/pdfplumber/files/5902526/err_test1.pdf)

when i debug the code after pdfplumber.pdf.PDF(file_path), i find the edges' coordinates have nagetive values:

![20210201154906](https://user-images.githubusercontent.com/32935654/106429200-18991880-64a5-11eb-8ab4-db61c5a5287a.png)

### the 2nd pdf:
[err_test2.pdf](https://github.com/jsvine/pdfplumber/files/5902557/err_test2.pdf)

And the second pdf has a opposite performance, the pdf lack the edges of the table

```python
from pdfplumber.pdf import PDF
pdf = PDF('./err_test2.pdf')
pdf.pages[0].to_image().draw_rects(pdf.edges,stroke=("blue"),stroke_width=2).draw_lines(pdf.lines,stroke=("red"), stroke_width=1).annotated.show()
```
![20210201155344](https://user-images.githubusercontent.com/32935654/106429674-b987d380-64a5-11eb-9abb-7a71805e785b.png)

At the same time, i try to use a table parser tool ``camelot`` (camelot extract table based on ``pdfminer`` when read pdf by using ``stream`` flavor), and ``camelot`` extract more information:

```python
import camelot
tables = camelot.read_pdf(file_path, flavor="stream")
tables[0].to_html('./result_table.html')
```

![20210201161310](https://user-images.githubusercontent.com/32935654/106431610-7b3fe380-64a8-11eb-803b-236a518ebf7c.png)

but camelot has a terrible API to user.

So i ask your help to check the problem.

## Environment

- pdfplumber version: [0.5.23]
- pdfminer version: [20191125]
- camelot-py version: [0.8.2]
- Python version: [3.6.2]
- OS: [Linux]

**Comment by jsvine** [comment]
Thanks for raising these issues, @jackstraws! 

## On the 1st PDF

I'm not sure *why* the PDF objects with negative-value coordinates, but (a) it seems to be intrinsic to the PDF, and (b) I don't think the negative values are causing problems here.

What is odd and potentially problematic, however, are how the rectangles are specified. Running this code:

```python
pdf = pdfplumber.open("err_test1.pdf")
p0 = pdf.pages[0]
im = p0.to_image()
im.draw_rects(p0.rects)
```

... produces this:

![err_test1](https://user-images.githubusercontent.com/534702/106844866-b2b0ba80-6677-11eb-8529-d8550f335353.png)

I'm not quite sure why those rects are so thick, but it's worth looking into.


 ## On the 2nd PDF

This problem stems from the fact that the PDF has "drawn" the outer rectangle of the table as a `mllll` path instead of an `mlllh` path; as a result, `pdfminer.six` sees that shape as a "curve" instead of a "rect." See [here](https://github.com/pdfminer/pdfminer.six/blob/c8cceb7c58deec9e647be6d3957e03442770bdd0/pdfminer/converter.py#L95) for details on what I mean by that. I'm working on a PR to `pdfminer.six` that would address this, but in the meantime, you should be able to extract the table by using the curves in the extraction. For instance:

```python
pdf = pdfplumber.open("err_test1.pdf")
p0 = pdf.pages[0]
im = p0.to_image()
im.debug_tablefinder({
    "explicit_vertical_lines": p0.curves,
    "explicit_horizontal_lines": p0.curves,
})
```

... produces this:

![err_test2](https://user-images.githubusercontent.com/534702/106845404-e04a3380-6678-11eb-9bd2-afd6c08385f2.png)

And to actually extract the data, rather than visually debug the table:

```python
p0.extract_table({
    "explicit_vertical_lines": p0.curves,
    "explicit_horizontal_lines": p0.curves,
})
```

**Comment by jackstraws** [comment]
Thanks for your help, and it's a useful way to parse some pdfs which like the 2nd pdf.

I also noticed that ``pdfminer.six`` has a wrong result of the 1st pdf(negative coordinate values)

**Comment by jsvine** [comment]
Great, glad to hear it! On this note:

> I also noticed that pdfminer.six has a wrong result of the 1st pdf(negative coordinate values)

Yes, `pdfplumber` depends entirely on `pdfminer.six` for extracting coordinate values. If you believe the extracted coordinates are wrong, it's worth raising an issue in that repository's issues.

**Comment by Shiwei-Du** [comment]
Thank you jsvine, 
Thank you jackstraws. 
Actually, I had the same issue like jackstraws.  Now it works !
