### ISSUE TITLE
extract_words is slow

### ISSUE THREAD

**Issue by sreeni5493** [jsvine/pdfplumber#453]
```
s = timeit.default_timer()
words = page.extract_words(use_text_flow=True)
e = timeit.default_timer()
print('For word extraction:', (e - s), 'seconds')
```

The above code for a sample like below takes 5.42 seconds
[v1.pdf](https://github.com/jsvine/pdfplumber/files/6692746/v1.pdf)

This is a lot for a simple word extraction. Is there anyway I can optimize with either parameters or other options or even in code?

**Comment by jsvine** [comment]
This won't speed it up, but it will give you a sense of whether the bottleneck is in the page parsing or word extraction:

```python
t0 = timeit.default_timer()
# Calling page.chars forces pdfplumber to parse the page, 
# after which the parsed objects are cached
assert page.chars
t1 = timeit.default_timer()
print('For page parsing:', (t1 - t0), 'seconds')
words = page.extract_words(use_text_flow=True)
t2 = timeit.default_timer()
print('For word extraction:', (t2 - t1), 'seconds')
```

**Comment by jsvine** [comment]
Using the code above, I have confirmed that the bottleneck is in the page parsing, not the word extraction:

```
For page parsing: 6.844469053000001 seconds
For word extraction: 0.44166334599999857 seconds
```

Since the page-parsing logic is largely governed by `pdfminer.six`, there's not much we can do in this repository to speed things up. If you'd like, you can file an issue with `pdfminer.six`, with demonstration code tailored to that project.
