### ISSUE TITLE
Missing last row from intermediate tables, when using mixed strategy

### ISSUE THREAD

**Issue by bobluda** [jsvine/pdfplumber#466]
## Describe the bug

When there are multiple tables in one page and when using a mixed strategy settings: `{"vertical_strategy": 'lines', "horizontal_strategy": 'text'}`.

Only the last row of the last table is correctly extracted.
Other tables are only partially extracted, their last row is missing.

## Code to reproduce the problem

For more details, see related PR https://github.com/jsvine/pdfplumber/pull/467

```python
pdf = pdfplumber.open(pdf_path)
page = pdf.pages[0]

table_settings = {
	"vertical_strategy": "lines",
	"horizontal_strategy": "text"
}

extracted_tables = page.extract_tables(table_settings)

for table in extracted_tables:
	print(table)
```

## PDF file

https://github.com/bobluda/pdfplumber/blob/issue-466/tests/pdfs/issue-466-example.pdf

## Expected behavior

Should extract the last row of every tables.

## Actual behavior

Only extracts the last row of the last table.

## Screenshots

N/A

## Environment

- pdfplumber version: 0.5.28
- Python version: 3.6

**Comment by jsvine** [comment]
Hi @bobluda, and many thanks for raising this issue. Previously, @samkit-jain raised a related issue, https://github.com/jsvine/pdfplumber/issues/265. At the time, I had mixed opinions about @samkit-jain's proposed solution because it seemed like the specific example in that issue could be resolved by cropping the page. But the new example you share identifies another, less-resolvable problem with the current behavior — the scenario when there are multiple tables on a page. For ease of reference, here is the PDF you shared with `page.to_image().debug_tablefinder({ **tablesettings, **{ "intersection_tolerance": 10 })` run on it:

![issue-466-example-adjusted](https://user-images.githubusercontent.com/534702/125798089-70bf8531-ddad-41a2-9a92-800ffd86bef8.png)

Table identification for the final table works *because* it is the final table, while the identification for the first table is stymied because the current behavior only grabs the `bottom` of the final chunk of text (which belongs to the final table, not the first one).

This finally convinces me that the current behavior does indeed need to be fixed, and your proposal in the PR seems like a reasonable one (though I may slightly tweak the approach without changing the logic or test). Many thanks to you and @samkit-jain for the suggestion.

**Comment by jsvine** [comment]
Closed via merging https://github.com/jsvine/pdfplumber/pull/467
