### ISSUE TITLE
Jumbled text extracted

### ISSUE THREAD

**Issue by ParkvilleData** [jsvine/pdfplumber#468]
## Describe the bug

Hi, when using pdfplumber sometimes, on some pdfs, the text comes out jumbled. On the same pdf I am getting the following text extracted.

Jumbled:

```
 \nviR olecso verbeytd h iasge remeanert t hoosefP  oewrlWionrekr e,E lcetcrail \nTrdaespseoirnn clutdhiopsneegorf  mrinEgel ctriFcitatilon rgC  abJloeni tweorr k, \nMetTeerc nhiica,An pperntei ecnggaedi nE elcitacrlL,i wnoerrk,Ce abJloeni ter, \nMetTeerc nhiicaonrE  lcetcraiFlit tiwnogr PkE,R UO peartosre,im 
```

Unjumbled:

```
(i) all relevant information about the change, including the \nnature of the change; and \n  (ii) information about what the employer reasonably \nbelieves will be the effects of the change on the \nemployees; and \n  (iii) information about any other matters that the employer \nreasonably believes are likely to affect the employees; \nand \n  (c) invite the relevant employees to give their views about the \nimpact of the change (including any impact in relation to \ntheir family or caring responsibilities)
```

## Code to reproduce the problem

The code calling pdfplumber

```
 with pdfplumber.open(pdfFile) as pdf:
            for pdf_page in pdf.pages:
                try:
                    text = pdf_page.extract_text()
                    all_text[page_count] = text
                except:
                    print(pdf_page + ": " + pdf_page.extract_text())
                if print_pages:
                    print(all_text)
                page_count += 1
            pdf.close()
            return(all_text)
```
## Environment

- pdfplumber version: [0.5.28]
- Python version: [3.8.5]
- OS: [Linux]

## Additional Info
When I copy and paste the text into a word document and then save as a pdf it works better as the text isn't jumbled.
Is it having trouble with the font for that particular pdf?

Really appreciate any help,
Thanks

**Comment by jsvine** [comment]
Hi @ParkvilleData, and thanks for your interest in this library. Could you provide a PDF for which you've observed this happening?

**Comment by ParkvilleData** [comment]
Hi, Sorry for the delay. Here is the PDF.

[ae410508.0.pdf](https://github.com/jsvine/pdfplumber/files/6851782/ae410508.0.pdf)

Thankyou for you help,

**Comment by samkit-jain** [comment]
Thanks for sharing the PDF @ParkvilleData but I am not able to reproduce the issue. Getting the text in the right format. Would it be possible for you to share a reproducible code? For example, since the code you shared was incomplete, I did some changes to make it runnable and this was the result
```python
import pdfplumber

print_pages = True
page_count = 0
all_text = {}

with pdfplumber.open("file.pdf") as pdf:
    for pdf_page in pdf.pages:
        try:
            text = pdf_page.extract_text()
            all_text[page_count] = text
        except:
            print(str(page_count) + ": " + pdf_page.extract_text())
        if print_pages:
            print(all_text)
        page_count += 1
    pdf.close()
```

Running it yields the expected output for page 137 for which you have shared the text above.

**Comment by ParkvilleData** [comment]
So, sorry. I uploaded the wrong pdf. Here is the pdf.

[ae410508.pdf](https://github.com/jsvine/pdfplumber/files/6859284/ae410508.pdf)

I removed the print_pages variable from the code.

```
import pdfplumber
import sys

page_count = 0
all_text = {}

with pdfplumber.open(sys.argv[1]) as pdf:
    for pdf_page in pdf.pages:
        try:
            text = pdf_page.extract_text()
            all_text[page_count] = text
        except:
            print(str(page_count) + ": " + pdf_page.extract_text())
        page_count += 1
    pdf.close()
print(all_text)
```

I run this in python3 passing the pdf file to it via command line and this is some of the output I get.

```
d  \nivP owrecAours atlrLitaed m ployeeneggsaed i tnh orsloee dset iadlb eeolwa;n d \nv TheC ommuinctaionEsel,ct rlic,Ea elctorniEcn,eg yr Ifnromatoin,P otsa,l \nPlumbainnAdgll d iS eerevsiU cnoino fA utsarl(iCaE P)UE elcctarBliar nhc ainstd  \nmembesr. \nviR olecso verbeytd h iasge remeanert t hoosefP  oewrlWionrekr e,E lcetcrail \nTrdaespseoirnn clutdhiopsneegorf  mrinEgel ctriFcitatilon rgC  abJloeni tweorr k, \nMetTeerc nhiica,An pperntei ecnggaedi nE elcitacrlL,i wnoerrk,Ce abJloeni ter, \nMetTeerc nhiicaonrE  lcetcraiFlit tiwnogr PkE,R UO peartosre,im -lselkdli aobur \nasistsinEgl terciTcaradle sspoe,nr EelcctarTliar deAss istsnatC,o ntsruocnt i\nProjLeecaetdr(  CPLo re1 qu)vi alent. \nviIint h eev nett haatnc yur rnete mpyleoie cso vebryet dht ee ramnscd o ndiotfi ons \ntheP owrecroA usatlriWaor kpel aAecgermte2 n007 (CEPUi)n   rtloheeo  
```

**Comment by jsvine** [comment]
Thanks for sharing this new PDF, @ParkvilleData. I think it will help to focus on specific pages that display this issue, rather than the entire PDF, since the PDF contains both fully-digital pages (which pdfplumber handles well) and OCR'ed pages (which display the jumbling you're talking about). So let's choose, for now, the sixth page:

```python
print(pdf.pages[5].extract_text()
```

That produces, which, is indeed jumbled:

```
Powercol�ru stralia Ltd/CPittyi Power
&
CEPU EnterprAigsree emen2t0 13- 2016
```

So let's take a closer look, using pdfplumber's visual debugging:

```python
p = pdf.pages[5]
im = p.to_image()
im.draw_rects(p.chars) # Draw a rectangle around each character object
im.save("debug.png")
```

The result indicates a few issues, including that the characters of distinct words are overlapping substantially (see the parts with with a higher opacity), and that the characters extend far beyond where you'd visually expect them to be:

<img width="533" alt="Screen Shot 2021-08-19 at 9 31 40 AM" src="https://user-images.githubusercontent.com/534702/130077400-38a252f6-7579-47e6-a3c5-be27f885c75f.png">

Next, let's examine the actual character objects `p.chars`. I've saved a CSV version of their main attributes here: 
[p6-chars.csv](https://github.com/jsvine/pdfplumber/files/7014723/p6-chars.csv)

If you look at that file, you can see that the characters are extracted in the order you would expect, *but* that `x` positions are a bit awry. For instance, let's focus on the "Enterprise Agreement" part:

| fontname   |      x0 |     top |      x1 |   bottom | text   |
|------------|---------|---------|---------|----------|--------|
| Fd354352   | 143.29  | 306.464 | 160.89  |  324.064 | E      |
| Fd354352   | 160.89  | 306.464 | 178.49  |  324.064 | n      |
| Fd354352   | 178.49  | 306.464 | 196.09  |  324.064 | t      |
| Fd354352   | 196.09  | 306.464 | 213.69  |  324.064 | e      |
| Fd354352   | 213.69  | 306.464 | 231.29  |  324.064 | r      |
| Fd354352   | 231.29  | 306.464 | 248.89  |  324.064 | p      |
| Fd354352   | 248.889 | 306.464 | 266.489 |  324.064 | r      |
| Fd354352   | 266.489 | 306.464 | 284.089 |  324.064 | i      |
| Fd354352   | 284.089 | 306.464 | 301.689 |  324.064 | s      |
| Fd354352   | 301.689 | 306.464 | 319.289 |  324.064 | e      |
| Fd354352   | 319.289 | 306.464 | 336.889 |  324.064 |        |
| Fd240      | 261.25  | 306.961 | 278.6   |  324.311 | A      |
| Fd240      | 278.6   | 306.961 | 295.95  |  324.311 | g      |
| Fd240      | 295.95  | 306.961 | 313.3   |  324.311 | r      |
| Fd240      | 313.3   | 306.961 | 330.65  |  324.311 | e      |
| Fd240      | 330.65  | 306.961 | 348     |  324.311 | e      |
| Fd240      | 348     | 306.961 | 365.35  |  324.311 | m      |
| Fd240      | 365.349 | 306.961 | 382.699 |  324.311 | e      |
| Fd240      | 382.699 | 306.961 | 400.049 |  324.311 | n      |
| Fd240      | 400.049 | 306.961 | 417.399 |  324.311 | t      |

Notice how the `x0` position is `301.689` for the final `e` in "Enterprise" but is `261.25` for the `A` in Agreement, i.e., *behind* it? 

We can examine this more visually by running this code, knowing (from the CSV) the specific character indexes of "Enterprise" (rendered in blue) and "Agreement" (in red):

```python
BLUE=(0, 0, 255, 50)
RED=(255, 0, 0, 50)
im.reset()
im.draw_rects(p.chars[44:54], fill=BLUE, stroke=BLUE)
im.draw_rects(p.chars[55:64], fill=RED, stroke=RED)
im.save("debug.png")
```

<img width="473" alt="Screen Shot 2021-08-19 at 9 30 32 AM" src="https://user-images.githubusercontent.com/534702/130078939-170510aa-9dcd-4513-915b-9cf33e215d65.png">

This confirms to me that the problem here is the positional values provided by whatever OCR software was used to digitize the scanned parts of this PDF. One option would be to re-OCR with more accurate OCR software. In the meantime, however, you can use this code to extract the text:

```python
from pdfplumber.utils import cluster_objects

def extract_ocr_text(page):
	line_chars = cluster_objects(page.chars, "top", tolerance=5)
	lines = [ "".join(c["text"] for c in chars) for chars in line_chars ]
	return "\n".join(lines)
```

Running this, for instance:

```python
print(extract_ocr_text(pdf.pages[5]))
```

... produces:

```
Powercor l�ustralia Ltd/CitiPower Pty
&
CEPU Enterprise Agreement 2013 -2016
```

I'm considering this issue solved/resolved, but feel free to continue the conversation here if you have questions.
