### ISSUE TITLE
pdfplumber 0.5.28 requires pdfminer.six==20200517, but you have pdfminer-six 20211012 which is incompatible

### ISSUE THREAD

**Issue by alexreg** [jsvine/pdfplumber#531]
## Describe the bug

Upon running `pip install pdfplumber`, I get the following.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pdfplumber 0.5.28 requires pdfminer.six==20200517, but you have pdfminer-six 20211012 which is incompatible.
```

This is an awfully restrictive dependency, that is naturally liable to create conflicts. Perhaps you could loosen it to `pdfminer.six>=20200517` (possibly with `<=` bound too)?

## Environment

- pdfplumber version: 0.5.28
- Python version: 3.9.7
- OS: macOS 12.0.1

**Comment by jsvine** [comment]
Hi @alexreg, and glad to see you around here again! Unfortunately for you, this pinned dependency is intentional and unlikely to change in the immediate future. The main reason is that `pdfminer.six`, while relatively mature, has introduced breaking changes from time to time, and does not use semantic versioning. Two bits of good news, though:

- `pdfplumber` will *likely* work with whatever `pdfminer.six` version you prefer, so feel free to upgrade the latter. You'll get a conflict warning, but can override/ignore that.

- The next `pdfplumber` release will upgrade the pinned version of `pdfminer.six` to the latest.

**Comment by alexreg** [comment]
@jsvine Thanks for the clarification. That makes sense. Indeed, it's a shame that pdfminer.six doesn't use semver. (Have you tried to convince them to adopt it?)

**Comment by jsvine** [comment]
I haven't tried lobbying for that, but the maintainers appear to have decided against it — cf.: https://github.com/pdfminer/pdfminer.six/issues/154#issuecomment-576911835

> We are not going to use semver (because pypi will get untenable confused).

**Comment by alexreg** [comment]
Ah, that's a shame, but fair enough. I suppose I'll just ignore the "error" and treat it more like a warning.
