### ISSUE TITLE
Cannot locate a two column table without any borders

### ISSUE THREAD

**Issue by ayusonkj** [jsvine/pdfplumber#566]
## Describe the bug

I have multiple tables in a pdf page, but only the two column table is not being identified

## Code to reproduce the problem

```
def get_table_boundaries(pdf: str) -> List[List[str]]:
    tables = []
    with pdfplumber.open(pdf) as pdf:
        for page in pdf.pages:
            if page.find_tables():
                settings = {
                    "vertical_strategy": "explicit",
                    "horizontal_strategy": "explicit",
                    "explicit_vertical_lines": page.curves + page.edges,
                    "explicit_horizontal_lines": page.curves + page.edges,
                }
                bboxes = [
                    table.bbox
                    for table in page.find_tables(table_settings=settings)
                ]
                for bbox in bboxes:
                    x0, y0, w, h = bbox
                    table_rect = [f"{x0}", f"{y0}", f"{w}", f"{h}"]
                    tables.append(table_rect)

    return tables
```

## PDF file
[p17_test.pdf](https://github.com/jsvine/pdfplumber/files/7716884/p17_test.pdf)

## Expected behavior

all tables are identified

## Actual behavior
only the two column table without the borders are not identified. only the headers are identified

## Screenshots

*If applicable, add screenshots to help explain your problem.*
[p17_table_captured.pdf](https://github.com/jsvine/pdfplumber/files/7716898/p17_table_captured.pdf)

![image](https://user-images.githubusercontent.com/89957740/146134810-811acf9d-be68-4236-a0e0-cc6aaa2e3191.png)

the rectangle drawings shows the coordinates/tables identified. as you can see, other tables are identified successfully, however, the two column table, was not identified
## Environment

- pdfplumber version: 0.5.28
- Python version: 3.9.6
- OS: Ubuntu 20.04

## Additional context

*Add any other context/notes about the problem here.*

**Comment by jsvine** [comment]
Hi @ayusonkj, and thanks for your interest in this library. A couple of things appear to be happening.

Due to a prior bug in `pdfminer.six` (the library we depend on for accessing PDF object information), `.curve` objects were not being extracted correctly. In your case, those light red lines are the curves, and not extracting those correctly makes it hard to identify the tables. 

`pdfminer.six` has since fixed that bug, and this new version will be available in the next release of `pdfplumber`. In the meantime, you can manually upgrade `pdfminer.six` by running `pip install pdfminer.six==20211012`. You will get a warning about incompatibility, but you can ignore that. Once you upgrade, the final line of the following code ... 

```python
import pdfplumber

pdf = pdfplumber.open("p17_table_captured.pdf")
page = pdf.pages[0]
im = page.to_image()

im.reset().draw_lines(page.edges + page.curves, stroke="green", stroke_width=2)
```

... should return an image that looks like this, providing evidence that the `.curve` objects are being correctly parsed:

![image](https://user-images.githubusercontent.com/534702/146487715-5ff28901-208a-4e50-82eb-257ac96a6e21.png)

Even so, there's another issue, which is that the left-side of many of the tables does not have any explicit border/line marking it, e.g., here:

<img width="35" alt="Screen Shot 2021-12-16 at 11 11 39 PM" src="https://user-images.githubusercontent.com/534702/146487740-09406a71-829f-413e-b1a0-fd61c99aab1d.png">

To handle that, you may have to write some more explicit logic identifying where those borders *should* be. I'd recommend calculating the `x0, top, x1, bottom` of each of those lines and passing them to `explicit_vertical_lines`.

Closing this issue for now, since the upcoming release fixes the fixable parts of this, but feel free to continue the discussion here.

**Comment by ayusonkj** [comment]
I understand, thank you.
