### ISSUE TITLE
Size measures char width when upright = False

### ISSUE THREAD

**Issue by suedunham** [jsvine/pdfplumber#663]
## Describe the bug
I don't know if this is a bug per se. I'm getting chars with varying values for ``size`` in a word where ``upright=False``. This corresponds with the difference in ``y`` values on the page, but it doesn't describe the font size well.

*A clear and concise description of what the bug is.*
For instance, There is a vertical abbreviation on the file I'm looking at (I don't think I can share it) with the text, "Pers.". In this case, ``direction=-1`` in addition to ``upright=False``. Eyeballing the font, it looks to be about 7-pt., but the ``extract_words`` method breaks each character into its own word with the sizes of 4.350000000000023, 3.69575999999995, 2.9023200000000315, 3.3338400000000092, and 2.178480000000036.

All characters have the same values for ``x0`` and ``x1``, with the difference being 6.960000000000036.

## Code to reproduce the problem
It's a big file using a copyrighted pdf. I am using the following method on several sections of each page.

*Paste it here, or attach a Python file.*
```
extract_words(keep_blank_chars=True,
              vertical_ttb=False,
              extra_attrs=['fontname,' 'size', 'stroking_color', 'non_stroking_color'])
```

## PDF file

*Please attach any PDFs necessary to reproduce the problem.*

*If you need to redact text in a sensitive PDF, you can run it through [JoshData/pdf-redactor](https://github.com/JoshData/pdf-redactor).*

## Expected behavior

*What did you expect the result __should__ have been?*
I'd think that the ``size`` determination would rotate with the text, measuring the ``x`` differential for vertical text rather than the ``y``.

## Actual behavior

*What actually happened, instead?*
``size`` stayed with the ``y`` dimension as it does with upright text.

## Screenshots

*If applicable, add screenshots to help explain your problem.*

## Environment

- pdfplumber version: [e.g., 0.7.0]
- Python version: [e.g., 3.9.12]
- OS: Windows 10

## Additional context

*Add any other context/notes about the problem here.*
-pdfminer.six version: 20220524

**Comment by jsvine** [comment]
Hi @suedunham, and thanks for your interest in this library. Thanks, too, for raising an interesting issue. Without a specific PDF to examine, it's difficult to know whether I'm fully understanding the question and/or to provide a definitive answer, but a few notes that may be helpful:

The `size` attribute comes directly from `pdfminer.six` (this library's main dependency). There, the calculation is relatively blunt — `size` is the character's width if the *font* (not the orientation) is vertical, else it is the character's height: https://github.com/pdfminer/pdfminer.six/blob/e19aea932d10938a995e89aea79fb304da5a82ff/pdfminer/layout.py#L387-L390

To do the grouping in the manner you're hoping for, your best bet may be to create a new attribute on each char representing the height for `upright==True` characters and the width for `upright==False` characters. That said, I'm not 100% confident in that suggestion without being able to see the PDF.

Closing for now, since this seems not quite to be a bug, but feel free to continue the conversation here.
