### ISSUE TITLE
Re-process a page

### ISSUE THREAD

**Issue by lifepillar** [jsvine/pdfplumber#664]
I would like to re-process a single page of a document, without creating a new PDF object. For instance:

```python
pdf = pdfplumber.open("some.pdf") 
# (Modify, say, the first page in the original PDF)
new_page1_stream = # the updated page, as a byte stream
with pdfplumber.open(new_page1_stream) as pdf2:
  pdf.pages[0] = pdf2.pages[0]  # Replace the old page with the updated page
```

But pages have references to their PDF documents, and the code above would break those—and possibly something else. Is there a better way?

**Comment by jsvine** [comment]
Hi @lifepillar, and interesting goal! There are parts of pages (in general, not just this library's modeling of them) that do indeed depend on PDF-level resources, so I'm not sure there's a straightforward way to wholesale update a page in a generalized manner. The correct/expected behavior probably also depends on what, specifically, is being modified. There may be a more complex way to get there, however, and I'd welcome proposals on how to achieve that.

In the meantime, let's assume that you want to want to copy over the standard objects on the page (`.char`, `.rect`, etc.). In that case, I'd try this:

```python
pdf.pages[0]._objects = pdf2.pages[0].objects()
```

Closing this for now, but feel free to continue the conversation.

**Comment by lifepillar** [comment]
Thanks for the feedback! Yes, I have realized that what I was trying rows against the current: as you say, a PDF document is a cohesive structure. I am approaching my problem differently now. Thanks again!
