### ISSUE TITLE
some times detect more line than the exist lines

### ISSUE THREAD

**Issue by Loovelj** [jsvine/pdfplumber#80]
some time , when I use detect_table(),I find it detected more line than exist lines，[example](https://i.loli.net/2018/09/04/5b8df7f27198a.jpg)

**Comment by jsvine** [comment]
Hi, @Loovelj. Unfortunately, I get this error when I try to access your example:

<img width="622" alt="screen shot 2018-09-11 at 9 08 36 am" src="https://user-images.githubusercontent.com/534702/45362248-59292c00-b5a2-11e8-8e3d-939617df67de.png">

Could you provide more detail, such as the PDF and code you're using?

In general, though, there will often be times when the output of `.detect_table()` is different than you'd expect, because of quirks in how the PDF's authors constructed the table. We can try to come up for heuristics for handling the most common types of edge-cases, but you may have to use custom-written code to resolve the more uncommon ones.

**Comment by Loovelj** [comment]
![5b8df7f27198a](https://user-images.githubusercontent.com/10558917/45807727-bd609400-bcf6-11e8-80a4-4810f7fb9cbe.jpg)

OK ,thanks！I'm going to try others methods

**Comment by jsvine** [comment]
Thanks! It's possible that there are additional lines or rectangles in the PDF that are not visible — perhaps because they're the same color as the background, or because they're hidden behind the background.
