### ISSUE TITLE
[Question] Create a pandas DataFrame from plumber efficiently

### ISSUE THREAD

**Issue by Mahendra114027** [jsvine/pdfplumber#82]
### How to create a pandas DataFrame using pdfplumber with high efficiency and less time
Hi, 
I came across pdf plumber while i was researching to extract text from PDF documents. I am currently working with pandas to get proper dataframe from the plumber object.

**ISSUE** : My issue is the time it takes to generate a dataframe for all the supported objects provided by the plumber. Hence, I want to minimize time for generating object dataframe. Currently, it takes around 35 seconds for me to generate object dataframe for a 40 page PDF document. 

I am using the following code for generating page by page dataframe of the PDF :

`my_file = '../file_path/example.pdf'`
`pdf_object = pdfplumber.open(my_file)`

`char_df = pd.DataFrame()`
`for page in pdf_object.pages:`
    `temp_df = pd.DataFrame(page.chars)`
    `char_df = char_df.append(temp_df)`
`return char_df`

Similarly i repeat this for all other objects (lines, rects, curves, images.....)
I am new in pandas and have just started with plumber, so any help is appreciated.
Thanks in advance!!

**Comment by jsvine** [comment]
Hi @Mahendra114027. The conversion of a list of PDF objects to a pandas DataFrame is actually quite low-overhead. The bulk of the time your script takes is likely due, instead, just to `pdfplumber` extracting the object data from the PDF. That happens whenever you start accessing a PDF's object-attributes (e.g.,  `page.chars`).

Even so, you can simplify the DataFrame creation in the code you've shared by accessing all of the chars at once: `char_df = pd.DataFrame(pdf_object.chars)`.

**Comment by Mahendra114027** [comment]
Hi @jsvine . Main reason for raising this question was to minimize the time it takes to access pdf objects.
Accessing `chars` attribute of the `pdf_object` takes around 15.63 seconds to process a pdf of 40 pages.
How do I minimize the time it takes to access chars attribute. Is there any new release that will have a faster access of the pdf_object attributes (chars, lines, rects, etc...) or is there any other solution which is more time efficient  than this one.

**Comment by jsvine** [comment]
Unfortunately, there's no easy way to make big improvements pdf-object access. Future versions may have small efficiency improvements but, fundamentally, `pdfplumber` depends on [`pdfminer.six`](https://github.com/pdfminer/pdfminer.six) for pdf-object extraction. If `pdfminer.six` is able to speed up object extraction, then we can incorporate those improvements into `pdfplumber`. Otherwise, if you need a lot more speed, it's worth exploring PDF-parsing libraries in other languages. For instance (although I haven't tried these):

- https://github.com/yob/pdf-reader (Rust)
- https://github.com/unidoc/unidoc (Go)
- https://pdfbox.apache.org/index.html (Java)
