### ISSUE TITLE
The data is in a box. How to access the data in tabular form?

### ISSUE THREAD

**Issue by abhijit-z** [jsvine/pdfplumber#829]
The data is in a box. There are no lines separating the text in the box. But with eyes we can recognize the fields and values. How to access such text or table in a box?

**Comment by samkit-jain** [comment]
Hi @abhijit-z Appreciate your interest in the library. Request you to provide more information. Please share the PDF redacting any sensitive information, what you are trying to achieve, and what you have tried. Furthermore, since it looks more like a help request rather than a bug, request you to start a [discussion](https://github.com/jsvine/pdfplumber/discussions/new?category=q-a). Closing this issue for now. Feel free to continue the conversation.
