### ISSUE TITLE
dedupe_chars() method get error

### ISSUE THREAD

**Issue by 154192** [jsvine/pdfplumber#842]
![image](https://user-images.githubusercontent.com/30179436/226511592-82147c98-a2f7-41da-93fd-a2d6ad940eff.png)
[300218_2011.pdf](https://github.com/jsvine/pdfplumber/files/11024797/300218_2011.pdf)

**Comment by jsvine** [comment]
Thanks for raising this issue @154192. The intermediate issue appears to be that the fontnames for some some of the PDF's characters are being read as bytes — e.g., `b'RGJSAP+\xcb\xce\xcc\xe5'` — instead of strings. I'm not yet sure whether this is an issue with the PDF itself or with `pdfminer.six`, the library `pdfplumber` uses as its PDF parser. I hope to take a closer look soon.

**Comment by jsvine** [comment]
This should now be fixed in v0.9.0, but let me know if it's still not working for you.
