### ISSUE TITLE
table extract fails to recognize table

### ISSUE THREAD

**Issue by 5hubh0** [jsvine/pdfplumber#86]
import pdfplumber
pd = pdfplumber.open('file.pdf') 
pg = pd.pages[1].crop([32,125,555,268])
im = pg.to_image()

table_settings={
    "vertical_strategy": "lines", 
    "horizontal_strategy": "lines",
    "snap_tolerance": 3,
    "join_tolerance": 3,
    "edge_min_length": 5,
    "intersection_tolerance": 3,
    "intersection_x_tolerance": None,
    "intersection_y_tolerance": None,
}

im.debug_tablefinder(table_settings)
[file.pdf](https://github.com/jsvine/pdfplumber/files/2454517/file.pdf)

**Comment by 5hubh0** [comment]
Have already tried multiple settings without any sucess.

**Comment by jsvine** [comment]
It seems the source of the issue is that the lines in that table are represented as `curve` objects (at least as extracted by `pdfminer.six`), rather than `rect` or `line` objects (which is what `pdfplumber` uses for table extraction):

<img width="548" alt="screen shot 2018-10-10 at 9 40 13 pm" src="https://user-images.githubusercontent.com/534702/46775445-4f940080-ccd5-11e8-82d2-011fe4175795.png">

**Comment by ratulbhadury** [comment]
Hi @5hubh0 

It seems I am having exactly the same issue as you did with your PDFs somehow having key vertical/horizontal lines ended up being encoded within curves.

I'm curious...were you able to come up with a workaround or any local changes you made to pdfplumber that resolved your problem? If so, would be very grateful if you could share details.

Kind regards

**Comment by 5hubh0** [comment]
Unfortunately no. I had some pdf files coming in which were scanned copies having such tables, therefore it made sense to use computer vision libraries to identify the cells (still working on this, haven't made much progress) . Also, converting curves to lines is not a foolproof solution. You may use tabula. Nowadays it is very easy to train a Neural network on generated synthetic data to identify tables and/or table cells and have reliable performance.

> Hi @5hubh0
> 
> It seems I am having exactly the same issue as you did with your PDFs somehow having key vertical/horizontal lines ended up being encoded within curves.
> 
> I'm curious...were you able to come up with a workaround or any local changes you made to pdfplumber that resolved your problem? If so, would be very grateful if you could share details.
> 
> Kind regards

**Comment by FaizShah** [comment]
@5hubh0 can you expand on training neural networks on generated synthetic data? Any references or blog posts?

I'm dealing with a similar problem extracting form data. I have the original form and then I have a bunch of scanned pdfs of the form filled out. I could generate synthetic data but I dunno how to start on the neural network for extracting the data.

**Comment by 5hubh0** [comment]
From your question, it appears that you are working with a form with fixed areas where the text is entered then there is an easier way as the location of the text and fields are already known ... Only if it is dynamic and/or scanned pages only then computer vision may be used.

**Comment by FaizShah** [comment]
Hi @5hubh0, thanks for the quick response. I can add some more context.

The cells of the tables/forms will not have a fixed position on the page due to scanning however the layout is fixed. I can show examples.

I have these images: https://efdsearch.senate.gov/search/view/paper/6226BACC-0B43-408B-BD1A-A57078EEC0B2/

They come from this form template: https://www.ethics.senate.gov/downloads/pdffiles/cover1.pdf

However the scanned images can be skewed and cut off as in: https://efdsearch.senate.gov/search/view/paper/EED29B78-6F2F-44E0-9A8A-1FA7A904C50F/

I started trying OCR then using pdfplumber but the approach doesn't work very well. So I started [investigating using OpenCV](https://nanonets.com/blog/table-extraction-deep-learning/) to detect and match the page template. Is there a better approach?

**Comment by 5hubh0** [comment]
You may consider attaching the files. Since the format is known to you, you may select a feature as a point of reference in the scanned image and one or more features may be used to compute the scaling, rotation, skew and or distortion which is one way to go about it.

A practical way: you may consider using one or more of the following off the shelf tools https://github.com/galfar/deskew and/or  http://www.fmwconcepts.com/imagemagick/autotone/index.php and/or http://www.fmwconcepts.com/imagemagick/textcleaner/index.php and/or tesseract ocr

**Comment by LinanYaooo** [comment]
I've solved it by introducing curves objects in extracting settings. Since most of the table's edges were recognized as curves object, what you can try is to assign page's curve object to extraction_settings, in detail, assign page[x].curves to the corresponding page's extracting setting can solve this.
this is my try & works well
extraction_settings = {
    "vertical_strategy": "lines",     
    "horizontal_strategy": "lines",
    "explicit_vertical_lines": page[0].curves,         # used for extract table from page[0]
    "explicit_horizontal_lines": page[0].curves,    # used for extract table from page[0]
    "snap_tolerance": 3,
    "join_tolerance": 3,
    "edge_min_length": 3,
    "min_words_vertical": 3,
    "min_words_horizontal": 1,
    "keep_blank_chars": True,
    "text_tolerance": 3,
    "text_x_tolerance": 1.5,
    "text_y_tolerance": 1.5,
    "intersection_tolerance": 3,
    "intersection_x_tolerance": None,
    "intersection_y_tolerance": None,
}

**Comment by jsvine** [comment]
Cleaning up old issues, but feel free to reopen if you'd like to continue the discussion. Thanks!

**Comment by au-82** [comment]
I'm having similar issues with the table finder, I've check the page.object.items and I can see curve, char using this I have been able to extract some data from the table.

Looking at the data it is only processing the second bit of the table what you could say is the bottom half of the table.

**Comment by JonnoB** [comment]
The solution provided by @LinanYaooo is really great, it would be good if there could be an example or mention of this in the table extraction section as lines described by curves may be relatively common... It certainly is with the datasets I've been looking at!

**Comment by jsvine** [comment]
@JonnoB Good news, `.curves` are now incorporated into the default table-extraction approach as of the just-released `v0.9.0`. Thanks for the nudge!
